### ISSUE TITLE
[Progressing] First FULL Translation

### ISSUE THREAD

**Issue by ifshizuku** [ifshizuku/nextjs-zh-docs#3]
Welcome to the Next.js unofficial Chinese translation repository.

**If you would like to contribute to this project, please follow the instructions in this Issue.**

## Instructions

You can contribute by following these steps:

1. Select the **page or pages** you want to translate from **the list below** and **leave a comment** ("I want to translate {page}", etc), the maintainer will check the comments **periodically** and we will **update the list** and **reply to your comment** when your translation request is **approved**.
2. **Fork this repository** and translate your documents according to the **formatting instructions and glossary (coming soon...)**.
3. Initiate a **Pull Request** to this repository.
4. The maintainer will **review your PR** and provide **appropriate** instructions (including formatting and grammar, etc.) and ask the translator to **revise it** again. 

> **If** it is a general formatting issue or few grammar issues, the maintainer may consider checkout this PR and make the commit that links to this PR and then merge the branch locally to the main branch. The GitHub PR screen will still show the merge.

**If the page you claim is not translated within 48 hours, the corresponding claim will expire and the claimant will be removed from the page list in the corresponding position.**

## Page List

> **Based on English document title**

- [x] **Getting Started** ( @ifshizuku )

- [x] **Basic Features** ( @ifshizuku )

  - [x] **Pages**
  - [x] **Data Fetching**

    - [x] **Data Fetching Overview**
    - [x] **getServerSideProps**
    - [x] **getStaticPaths**
    - [x] **getStaticProps**
    - [x] **Incremental Static Regeneration**
    - [x] **Client-side data fetching**
  
  - [x] **Built-In CSS Support**
  - [x] **Layouts**
  - [x] **Image Component and Image Optimization**
  - [x] **Font Optimization**
  - [x] **Static File Serving**
  - [x] **Fast Refresh**
  - [x] **ESLint**
  - [x] **TypeScript**
  - [x] **Environment Variables**
  - [x] **Supported Browsers and Features**
  - [x] **Script Component**

- [x] **Routing** ( @ifshizuku )

  - [x] **Routing**
  - [x] **Dynamic Routes**
  - [x] **Imperatively**
  - [x] **Shallow Routing**

- [x] **API Routes** ( @ifshizuku )

  - [x] **API Routes**
  - [x] **Dynamic API Routes**
  - [x] **API Middlewares**
  - [x] **Response Helpers**
  - [x] **Edge API Routes (Beta)**

- [x] **Going to Production** ( @ifshizuku )
- [ ] **Deployment**
- [ ] **Authentication**
- [ ] **Testing**
- [ ] **Accessibility**
- [ ] **Guide**

  - [ ] **Building Forms with Next.js**

- [ ] **Advanced Features**

  - [ ] **Next.js Compiler**
  - [ ] **Preview Mode**
  - [x] **Dynamic Import** ( @xxxxue ) #2 
  - [x] **Automatic Static Optimization** ( @xxxxue ) #2 
  - [x] **Static HTML Export** ( @xxxxue ) #2 
  - [ ] **Absolute Imports and Module path aliases**
  - [ ] **Using MDX with Next.js**
  - [ ] **AMP Support**
  
    - [ ] **AMP Support**
    - [ ] **Adding AMP Components**
    - [ ] **AMP Validation**
    - [ ] **AMP in Static HTML export**
    - [ ] **TypeScript**

  - [ ] **Customizing Babel Config**
  - [ ] **Customizing PostCSS Config**
  - [ ] **Custom Server**
  - [ ] **Custom `App`**
  - [ ] **Custom `Document`**
  - [ ] **Custom Error Page**
  - [ ] **`src` Directory**
  - [ ] **Continuous Integration (CI) Build Caching**
  - [ ] **Multi Zones**
  - [ ] **Measuring performance**
  - [ ] **Middleware**
  - [ ] **Debugging**
  - [ ] **Error Handling**
  - [ ] **Source Maps**
  - [ ] **Next.js Codemods**
  - [ ] **Internationalized Routing**
  - [ ] **Output File Tracing**
  - [ ] **Security Headers**
  - [ ] **React 18**
  
    - [ ] **React 18**
    - [ ] **Streaming SSR**
    - [ ] **React Server Components (Alpha)**
    - [ ] **Switchable Runtime (Alpha)**

- [ ] **Upgrade Guide**
- [ ] **Migrating to Next.js**

  - [ ] **Incrementally Adopting Next.js**
  - [ ] **Migrating from Gatsby**
  - [ ] **Migrating from Create React App**
  - [ ] **Migrating from React Router**
  
- [ ] **FAQ**
- [ ] **API Reference**

  - [ ] **Next.js CLI**
  - [ ] **Create Next App**
  - [ ] **`next` Package**

    - [ ] **next/router**
    - [ ] **next/link**
    - [ ] **next/image**
    - [ ] **next/script**
    - [ ] **next/head**
    - [ ] **next/amp**
    - [ ] **next/server**
    - [ ] **next/streaming**
    - [ ] **next/future/image**

  - [ ] **Edge Runtime**
  - [ ] **Data Fetching**

    - [ ] **getInitialProps**
    - [ ] **getServerSideProps**
    - [ ] **getStaticPaths**
    - [ ] **getStaticProps**

  - [ ] **Static Optimization Indicator**
  - [ ] **next.config.js**

    - [ ] **next.config.js**
    - [ ] **Environment Variables**
    - [ ] **Base Path**
    - [ ] **Rewrites**
    - [ ] **Redirects**
    - [ ] **Headers**
    - [ ] **Custom Page Extensions**
    - [ ] **CDN Support with Asset Prefix**
    - [ ] **Custom Webpack Config**
    - [ ] **Compression**
    - [ ] **Runtime Configuration**
    - [ ] **Disabling x-powered-by**
    - [ ] **Disabling ETag Generation**
    - [ ] **Disabling HTTP Keep-Alive**
    - [ ] **Setting a custom build directory**
    - [ ] **Configuring the Build ID**
    - [ ] **Configuring onDemandEntries**
    - [ ] **Ignoring ESLint**
    - [ ] **Ignoring TypeScript Errors**
    - [ ] **exportPathMap**
    - [ ] **Trailing Slash**
    - [ ] **React Strict Mode**
    - [ ] **URL Imports**
    - [ ] **Build indicator**

**All documents (or most of them) will be proofread after they are translated. We are short of proofreaders, so if you are interested in proofreading, please contact me (i@seen.moe)**
